#apiVersion: v1
#kind: Namespace
#metadata:
#  name: sealyun
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fist
  namespace: sealyun
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fist
  template:
    metadata:
      labels:
        name: fist
    spec:
      containers:
      - name: fist
        image: lameleg/fist:latest
        command: ["./fist", "auth"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: fist
          mountPath: /etc/fist
      volumes:
       - name: fist
         secret:
           secretName: fist
           items:
           - key: cert.pem
             path: cert.pem
           - key: key.pem
             path: key.pem
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "1000m"
#         requests:
#           memory: "128Mi"
#           cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: fist
  namespace: sealyun
spec:
  type: ClusterIP
  clusterIP: 10.106.233.67
  ports:
  - name: fist
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: fist
